# Generated by Django 5.0.4 on 2024-05-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_rename_is_admin_user_is_emploee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_emploee',
            new_name='is_employee',
        ),
    ]
