# Generated by Django 5.0.4 on 2024-05-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_order_master_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master',
        ),
    ]
